export { ExerciseOneDotOne } from './1'
export { ExerciseOneDotTwo } from './2'
export { ExerciseOneDotThree } from './3'
export { ExerciseOneDotFour } from './4'
export { ExerciseOneDotFive } from './5'
